version: '3.4'

services:
  api:
    container_name: api
    build:
      context: .\Backend\
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - DB_HOST=database
      - DB_NAME=master
      - DB_PASSWORD=AD_acta0
    depends_on:
      - database
  frontend:
    container_name: frontend
    build:
      context: .\frontend\
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - api
  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "5002:1433"
    environment:
      MSSQL_SA_PASSWORD: "AD_acta0"
      ACCEPT_EULA: "Y"